
version: '3'
services:

  creditsystem-back-end:
    image: "creditsystem:1.0"
    container_name: creditsystem-back-end
    ports:
      - "8080:8080"
    environment:
      - SPRING.PROFILES.ACTIVE=default
  creditsystem-front-end:
    image: "creditsystem-fe:1.0"
    container_name: creditsystem-front-end
    ports:
      - "3000:3000"
    links:
      - creditsystem-back-end

